### ISSUE TITLE
NO_DISTNAME_PERMISSIONS hides other errors

### ISSUE THREAD

**Issue by dagolden** [andk/pause#112]
As I read the code, for a new upload, any failure to add permissions for the primary package will cause NO_DISTNAME_PERMISSIONS to be set.  However, in the mail summary, NO_DISTNAME_PERMISSIONS is checked first and shortcuts other error messages.

Put differently, NO_DISTNAME_PERMISSIONS is one of the last things to be checked during analysis, but is the first and only condition reported.

I think this might be obscuring messages about what actual errors are occurring.

**Comment by dagolden** [comment]
FYI, issue #134 addresses this

**Comment by wolfsage** [comment]
#134 was merged. Is this ticket set to be closed? Thakns

**Comment by andk** [comment]
Seems to me, it is. Closing now. Thanks!
