### ISSUE TITLE
Unanticipated problem with grandfathering package names

### ISSUE THREAD

**Issue by andk** [andk/pause#113]
Today I received a request from MSCHILLI and GAAS to enable MSCHILLI to upload a libwww-perl-6.06 and get it indexed. On Michael's first attempt Pause had rejected the upload with the famous

``` text
    This distribution name can only be used by
    users with permission for the
    package libwww::perl, which you do not have.
```

Indeed Gisle had no chance to pass Michael the permissions for the imaginary libwww::perl because they only exist in the comaint-relevant table ("perms").

As a quick workaround I gave Michael the perms manually and hope that the indexer will pick it up correctly.

``` text
mysql> insert into perms (package,userid) values ('libwww::perl','MSCHILLI');
Query OK, 1 row affected (0.00 sec)
```

The question is: how do we want the workflow to work for grandfathered package and new comaintainers. The manual approach is not attractive. Add them all to primeur? Enforce a change of the name is a bit too brutal for my taste. I'm unsure whether there are more options I'm currently not thinking of.

Thanks,

**Comment by rjbs** [comment]
I believe this is no longer a problem after dist-permission-tracking we added later.
