### ISSUE TITLE
UX: Dev releases and reindexing menu

### ISSUE THREAD

**Issue by andk** [andk/pause#122]
I just visited https://pause.perl.org/pause/authenquery?ACTION=reindex and picked from the offered file names two that matched the dev release pattern. Pause let me do this and pretended this would lead to a reindexing. But as a matter of fact nothing will happen because they are dev releases. Bad UX.

Thanks to Dave Rolsky for bringing this to my attention.

**Comment by charsbar** [comment]
#336 should have fixed this.
