### ISSUE TITLE
Index problem with bignum?

### ISSUE THREAD

**Issue by steve-m-hay** [andk/pause#124]
Why does 02packages.details.txt contain these entries for the bignum distro?:

bigint                             0.32  F/FL/FLORA/bignum-0.32.tar.gz
bignum                             0.32  F/FL/FLORA/bignum-0.32.tar.gz
bigrat                             0.32  F/FL/FLORA/bignum-0.32.tar.gz
Math::BigFloat::Trace              0.36  P/PJ/PJACKLAM/bignum-0.37.tar.gz
Math::BigInt::Trace                0.36  P/PJ/PJACKLAM/bignum-0.37.tar.gz

Specifically, why are the first three packages listed as in FLORA's 0.32 distro rather than PJACKLAM's 0.37 distro?

Both distros contain all five packages (and no others), and all five package $VERSIONs are bumped in 0.37 compared to 0.32.

**Comment by karenetheridge** [comment]
see also https://rt.cpan.org/Ticket/Display.html?id=86465

**Comment by andk** [comment]
Thanks for the poke, Karen. I just hit reindex in lieu PJACKLAM

**Comment by wolfsage** [comment]
I think this can be closed. (Index issues have been resolved)

**Comment by andk** [comment]
Oh, yes, closing. Thanks!
