### ISSUE TITLE
PAUSE distro absence from CPAN considered harmful?

### ISSUE THREAD

**Issue by mohawk2** [andk/pause#135]
I'm making a PR that will implement a `bin/pause-indexcheck` suitable for using before uploading distros. I intend to make it easy to use this under EUMM. This is considerably "challenging" when the PAUSE code isn't on CPAN.

If the codebase needs some wrangling to make it more suitable for putting on CPAN, I will be pleased to do that if someone will guide me on what needs doing.

**Comment by rjbs** [comment]
I'm not sure this issue serves any purpose at the moment.
