### ISSUE TITLE
feedback about pause feedback

### ISSUE THREAD

**Issue by jheidemann** [andk/pause#138]
From the public pause website, there's no obvious way to give feedback.

It seems like, as a part of the Perl ecosystem, something at PAUSE should point to how you want feedback.  I assume (hope!) it's bug reports here, but maybe you have some other method you prefer.

Suggestion: a link (perhaps after login) to github's issue tracker for PAUSE, or to a mailing list, or something.

(Thanks for the very useful tool, of course!)

**Comment by charsbar** [comment]
There is: https://pause.perl.org/pause/query?ACTION=pause_04about#credits , though it's rather hard to find...
