### ISSUE TITLE
Editing user info fails if CENSORED is in email address box

### ISSUE THREAD

**Issue by dagolden** [andk/pause#139]
In some cases, the form is populated with "CENSORED" in the public email box.  Submitting with that value fails email address validation.  We should do one of the following:
- not populate a box with "CENSORED" and just leave it blank
- ignore "CENSORED" on submission

I looked at the code and didn't feel confident editing the email validation section myself, so this is an issue, not a PR.

**Comment by Grinnz** [comment]
To note, this is populated by default if user info hasn't been set for the user before. So this affects basically everyone until they realize it's an issue, preventing them from successfully setting the cpan address to forward in the meantime.

**Comment by charsbar** [comment]
This should be fixed by #332.
