### ISSUE TITLE
When user drops primary perms, actually assign to a PAUSE custodial account

### ISSUE THREAD

**Issue by dagolden** [andk/pause#143]
If I understand correctly, ordinary PAUSE admins can't manage permissions without acting as another user.  So when a user drops primary perms, PAUSE admins can't then assign.

If that's true, then "drop primary" really ought to assign primary to some custodial account ("NOPRIMARY") so PAUSE admins can reassign primary if needed.

CC: @neilbowers

**Comment by ap** [comment]
This has come up separately in #169.

Currently, NPM is learning this lesson (c.f. azer/left-pad#4 and [HackerNews discussion](https://news.ycombinator.com/item?id=11340510)).

I suggest that dropping `f` should assign to ADOPTME rather than NOPRIMARY.

It would be sensible to still allow completely dropping firstcome for uploads of experiments that don’t end up going anywhere, but the form for that should create a request that a CPAN admin must then manually confirm.

**Comment by neilb** [comment]
It would be handy to give someone first-come, as it means (a) there is someone who can assign co-maint or ownership to someone else, and/or  (b) that PAUSE admins will have easier time doing those things.

There are at least three options:

 1. If there's an existing co-maint, promote them to first-come
 2. Give first-come to `ADOPTME`
 3. Give first-come to some new PAUSE admin account

The trouble with `ADOPTME` is that it sends a message which might not be appropriate.

There are a number of scenarios I can think of:

 * A module only has an 'f', who drops it. Giving it `ADOPTME` would be fine in that case.
 * A module has an 'f' and a single 'c'. The comaint has been doing all the releases recently, and so in many cases would be the right person to give first-come to. What if the co-maint has never done any releases? I still think the best approach is to promote the single co-maint.
 * A module has multiple co-maints. There are multiple sub-cases here (co-maints have never done a release, only one co-maint has ever been active, multiple active co-maints, etc). This case would probably need some looking into by PAUSE admins, and automatically picking a comaint to promote is probably not the right thing to do. Maybe this is where we have a new PAUSE id (`PADMIN`?). The PAUSE admins should be alerted, but we'd always be able to find such cases by grep'ing for the user in `06perms.txt`.

**Comment by charsbar** [comment]
With #328, giving up primary permissions transfers their permissions to ADOPTME. If this is inconvenient, please open a new issue (and maybe refer to this as well). I'm closing this for now.
