### ISSUE TITLE
strange users in 06perms.txt

### ISSUE THREAD

**Issue by chorny** [andk/pause#146]
Note: second column is CPAN id

```
ABW,AppConfig:,f
BEANZ,AnyEvent::,f
CHANSEN,Authen::Si,f
DAGOLDEN,Acme::Acme,f
DELON,App::Pando,f
DERF,App::Slack,f
DJACOBS,Atom::Java,f
DJERIUS,Astro::STS,f
DMOL,App::PerlW,f
Dist::Zilla::PluginBundle::CJFIELDS,:CJFIELDS,f
HDANIEL,Apache::Ac,f
IFUSCHINI,Apache2::A,f
INGY,Acme::YBFO,f
IOANNIS,Authen::Tc,f
JALYCAI,article_fe,f
JAMESGOL,asterisk::,f
KAORU,Algorithm:,f
MLAWREN,App::githo,f
MONSIEUR,App::get_f,f
NICWOLFF,Amazon::SQ,f
RKITOVER,Apache::GD,f
ROOTKWOK,Acme::Schr,f
SIMON,Acme::OneH,f
SYAGI,App::ProcT,f
TELS,Audio::Aud,f
WBUNTINE,Alvis::Bag,f
WILL,Array::Sor,f
WYANT,Astro::sat,f
ZBY,AI::Classi,f
```

**Comment by karenetheridge** [comment]
This looks like the results of a transient code error, combined with an apparent truncation of the PAUSE id to the maximum length. e.g. consider:

```
: [ether@jaeger]$; grep Acme::OneH 06perms.txt 
Acme::OneHundredNotOut,SIMON,f
SIMON,Acme::OneH,f
```

It should be safe to simply delete these bad entries.

**Comment by andk** [comment]
>>>>> On Tue, 17 Mar 2015 13:33:29 -0700, Karen Etheridge <notifications@github.com> said:

  > This looks like the results of a transient code error, combined with an
  > apparent truncation of the PAUSE id to the maximum length. e.g. consider:

  > : [ether@jaeger]$; grep Acme::OneH 06perms.txt
  > Acme::OneHundredNotOut,SIMON,f
  > SIMON,Acme::OneH,f

Agreed, they all happened on 15 Mar 2014, only CFIELDS happened in ancient times. 

  > It should be safe to simply delete these bad entries.

Done.

Thanks!
-- 
andreas

**Comment by karenetheridge** [comment]
Here are a few more that remain:

```
GBAUER,AssistantF,f
JALYCAI,article_fe,f
JKRASNOO,ApacheCook,f
Lingua::EN,,m
MSTPLBG,AllKnowing,f
NJENSEN,ApacheMysq,f
SEBDIAZ,AuthLLDAPS,f
```

**Comment by andk** [comment]
delete from primeur where package in ('GBAUER','JALYCAI','JKRASNOO','MSTPLBG','NJENSEN','SEBDIAZ');

delete from mods where modid='Lingua::EN';

Done, thanks Karen!
