### ISSUE TITLE
PAUSE using filenames to determine namespace instead of metadata

### ISSUE THREAD

**Issue by mperry2** [andk/pause#148]
I uploaded a file to PAUSE for one of my distributions and used the filename `2d5d6656f8959d2af700f2267c3cc1f4.tar.gz`. Then I received an email from PAUSE with the following contents. It looks like it was trying to get the package name from the filename rather than look at the file's contents or metadata therein.

```
The following report has been written by the PAUSE namespace indexer.
Please contact modules@perl.org if there are any open questions.

  User: MPERRY (Matt Perry)
  Distribution file: 2d5d6656f8959d2af700f2267c3cc1f4.tar.gz
  Number of files: 14
  *.pm files: 1
  README: Config-INI-Reader-Encrypted-0.01/README
  META-File: Config-INI-Reader-Encrypted-0.01/META.json
  META-Parser: Parse::CPAN::Meta 1.4404
  META-driven index: yes
  Timestamp of file: Thu Mar 26 17:11:03 2015 UTC
  Time of this run: Thu Mar 26 17:12:32 2015 UTC

This distribution name can only be used by users with permission for the
package 2d5d6656f8959d2af700f2267c3cc1f, which you do not have.
```

Result:
The last paragraph indicates that PAUSE it trying to parse the filename for some Perl-related significance.

Expected result:
PAUSE should look at the contents of the uploaded file to extract whatever metadata it needs. `META.json` and `META.yml` both contain a significant amount of metadata that can be used by PAUSE for whatever purpose it needs.

**Comment by andk** [comment]
>>>>> On Fri, 27 Mar 2015 15:45:42 -0700, Matt Perry <notifications@github.com> said:

  > I uploaded a file to PAUSE for one of my distributions and used the filename
  > 2d5d6656f8959d2af700f2267c3cc1f4.tar.gz. Then I received an email from PAUSE
  > with the following contents. It looks like it was trying to get the package
  > name from the filename rather than look at the file's contents or metadata
  > therein.

  > The following report has been written by the PAUSE namespace indexer.
  > Please contact modules@perl.org if there are any open questions.

  >   User: MPERRY (Matt Perry)
  >   Distribution file: 2d5d6656f8959d2af700f2267c3cc1f4.tar.gz
  >   Number of files: 14
  >   *.pm files: 1
  >   README: Config-INI-Reader-Encrypted-0.01/README
  >   META-File: Config-INI-Reader-Encrypted-0.01/META.json
  >   META-Parser: Parse::CPAN::Meta 1.4404
  >   META-driven index: yes
  >   Timestamp of file: Thu Mar 26 17:11:03 2015 UTC
  >   Time of this run: Thu Mar 26 17:12:32 2015 UTC

  > This distribution name can only be used by users with permission for the
  > package 2d5d6656f8959d2af700f2267c3cc1f, which you do not have.

  > Result:
  > The last paragraph indicates that PAUSE it trying to parse the filename for
  > some Perl-related significance.

  > Expected result:
  > PAUSE should look at the contents of the uploaded file to extract whatever
  > metadata it needs. META.json and META.yml both contain a significant amount of
  > metadata that can be used by PAUSE for whatever purpose it needs.

I'm not sure what you're after with this experiment. It's correct that
large parts of the infrastructure of the CPAN rely on filenames
reflecting distribution names. I don't know how strong the desire is in
the community to keep it that way or change it. In any case, PAUSE was
never the leader in such a change, the desire would have to come from
the community. So what is to be gained from your approach?

-- 
andreas

**Comment by mperry2** [comment]
> So what is to be gained from your approach?

You'd be parsing metadata from a file whose sole purpose is to supply the data you need in a machine readable format. What's to be gained from not following that approach?

The filename is the wrong place for for this information. Look at how it's failed when dealing with my distribution. The PAUSE web site says "you will never be able to upload a file with the same name again (not even after deleting it)." Therefore, if you assume that the filename is the name and version of the distribution, you might be wrong. For example, CPANTS is recommending that I add a license file to my distribution with the full text of the license. That's a good idea, but I can't upload the updated distribution file with the same filename. It's also not a new version of my module. Therefore I have to choose a filename that I can guarantee is unique. In this case a MD5 hash.

**Comment by dagolden** [comment]
In an ideal world, would the filename have significance?  No.

Do we live in that ideal world?  No.

This recent article of mine might help explain some of the history: http://www.dagolden.com/index.php/2414/this-distribution-name-can-only-be-used-by-users-with-permission/

The reality is that filenames -- due to historical accident -- do have semantic meaning.  This could and should be better documented.  But I don't see that it's going to change at this point in time.

**Comment by karenetheridge** [comment]
In the future we might be able to change this, but I think we'd need to require the existence of a well-formed META.* file first, which currently we do not do.
