### ISSUE TITLE
provide an SQLite-friendly moddata dump

### ISSUE THREAD

**Issue by rjbs** [andk/pause#166]
At QAH 2015, we discussed loading the module database into SQLite.  @andk suggested that the regularly-published database dump should be sufficient.

That file won't load into SQLite, and in general it looks like there is no set of switches to mysqldump to make it work.  There are some AWK scripts to convert the dumps, but I didn't have much luck with them in a quick check.

I don't mind giving another look to conversion tools, but I think it would be quite simple to produce a cronjob that did an export to SQLite directly.  I don't think this would be very expensive, but I could test it locally to find out.  (I'll have to finally set up MySQL for a bit! 😊)

Let me know if you'd like me to proceed in this way or some other way!

**Comment by dolmen** [comment]
Is that dump publicly available? Link?

**Comment by rjbs** [comment]
It's at http://pause.perl.org/pub/PAUSE/PAUSE-data/moddump.current.bz2

You will need to provide your PAUSE credentials.  Also available via rsync.  See doc/README

**Comment by andk** [comment]
No preference if it works:) My personal experiences with both mysql and sqlite were both painful. A quite pleasant DB experience was postgresql. But given your familiarity with sqlite, there is probably a way to get things moving away from mysql. As far as I can see the two constructs that stand in the way are autoincrement and enum. If we get rid of the two, then both switching and converting should become a breeze.

Having said that, I'm not sure what your vision is when you say "export to SQLite directly".

**Comment by rjbs** [comment]
I have been meaning to do this myself for some time, but I am going to be realistic and say that I'm not working on this right now.  Nonetheless, I'm assigning it to me, in the hopes that I can do it before QAH 2016. :-)

When I said "export to SQLite directly," I meant we might offer an sqlite database, rather than the SQL to create one.

If we were going to change the PAUSE backend, I would definitely recommend pgSQL over SQLite.  SQLite is just useful for offline testing, in my opinion.  It means you can run the test suite (with a small amount of deviation from production) on a box without the full database install.
