### ISSUE TITLE
Co-maint permissions not shown on "Change Permissions" page

### ISSUE THREAD

**Issue by tsibley** [andk/pause#167]
I'm co-maint on many packages, but none of them show up in the place that would let me give up co-maint:

![selection-001](https://cloud.githubusercontent.com/assets/79913/7383484/0634b8fe-edd5-11e4-9603-445b58c511fe.png)

This is on the "Change Permissions" page: https://pause.perl.org/pause/authenquery?ACTION=share_perms

**Comment by andk** [comment]
Thanks, fixed with commit 6bc15ed
