### ISSUE TITLE
Describe when to expect and when not to expect e-mails from PAUSE

### ISSUE THREAD

**Issue by szabgab** [andk/pause#174]
I was surprised by not getting a 2nd e-mail from PAUSE after uploading a development release, but I got the explanation already.

I think it would be useful to explain in http://pause.perl.org/pause/query?ACTION=pause_04about
when to expect e-mail from PAUSE and when not to expect one.

**Comment by andk** [comment]
Thanks, now documented in 04pause.html

**Comment by szabgab** [comment]
Thanks. Here is one for you: :cookie:
