### ISSUE TITLE
Tell supplicant when indexing fails due to case differences in module names

### ISSUE THREAD

**Issue by neilb** [andk/pause#175]
Indexing will fail if the supplicant tries to upload a module which is case-insensitively the same as a module in 06perms.txt, but case-sensitively isn't.

Recent case: Oleg tried to upload `Captcha::Nocaptcha`, which failed because CLARSON has permissions on `Captcha::noCAPTCHA`.

The email could explicitly say "Indexing failed because PAUSE treats package names case insensitively, so your module Captcha::Nocaptcha  conflicts with Captcha::noCAPTCHA, which is owned by CLARSON".

Or something like that.

**Comment by dagolden** [comment]
The message originates here: https://github.com/andk/pause/blob/master/lib/PAUSE/package.pm#L204-L207

We never actually find the conflicting package -- we just look for all owners of the case-insensitive package and if the uploader isn't listed, then it's a permissions failure.

The message could be revised to suggest that it's a case problem. Or with a link to MetaCPAN with a search on the lc name.  E.g. https://metacpan.org/search?q=captcha%3A%3Anocaptcha

Patches welcome.  :-)
