### ISSUE TITLE
Lock wait timeouts

### ISSUE THREAD

**Issue by dagolden** [andk/pause#176]
These seems to be cropping up more often than I'd like:
```
Status: Database error
======================

     module : CGI::Lite
     version: undef
     in file: CGI-Lite-3.00/lib/CGI/Lite.pm
     status : The PAUSE indexer could not store the indexing result in
             the DB due the following error: C< Lock wait timeout
             exceeded; try restarting transaction >. Please report the
             case to the PAUSE admins at modules@perl.org.
```
Do we need to tune the database or the timeouts to avoid this?

David

**Comment by andk** [comment]
I gave it a try (err, two tries) and have deployed the bump to 150 seconds timeout. Please reopen the ticket if the effect is not satisfying.

**Comment by perlancar** [comment]
This still happens from time to time. Perhaps automatically schedule a retry or something instead of forcing an author to perform a reindex manually? (I use a script, but still).

Saw this most recently on Jun 24, 2020:

Status: Database error
======================

     module : Filename::Image
     version: undef
     in file: Filename-Image-0.002/lib/Filename/Image.pm
     status : The PAUSE indexer could not store the indexing result in
             the DB due the following error: C< Lock wait timeout
             exceeded; try restarting transaction >. Please report the
             case to the PAUSE admins at modules@perl.org.

__END__
