### ISSUE TITLE
Include CPAN Testers link in the upload email

### ISSUE THREAD

**Issue by neilb** [andk/pause#178]
To raise awareness of CPAN Testers, but also to encourage authors to pay more attention to it, we could put a link to the CPAN Testers results for an upload in the first email you get from PAUSE. Something like:

```
The uploaded file

   Text-Autoformat-1.71_01.tar.gz

has entered CPAN as

 file: $CPAN/authors/id/N/NE/NEILB/Text-Autoformat-1.71_01.tar.gz
 size: 29097 bytes
  md5: d7f8373c77bc369c5df50d458fd9244d

No action is required on your part
Request entered by: NEILB (Neil Bowers)
Request entered on: Sat, 06 Jun 2015 21:01:45 GMT
Request completed:  Sat, 06 Jun 2015 21:02:17 GMT

CPAN Testers will start testing this upload very soon.
You can check the results at:

  http://cpantesters.org/distro/T/Text-Autoformat.html?grade=1&perlmat=1&patches=2&oncpan=2&distmat=1&perlver=ALL&osname=ALL&version=1.71_01

Thanks,
--
paused, v1049
```

That's an ugly long URL I know, but that's the link I _think_ we should send people to, if we're going to, and it's a plaintext email.

Neil

**Comment by karenetheridge** [comment]
I don't know about others, but I almost always find the matrix view more useful for tracking down issues:  e.g. http://matrix.cpantesters.org/?dist=Text-Autoformat+1.71  (and it's shorter, too!) :)

**Comment by wolfsage** [comment]
Possible patch attached

**Comment by neilb** [comment]
I think I did a PR for this as well ... ah yes:

> https://github.com/andk/pause/pull/190

**Comment by karenetheridge** [comment]
:+1

**Comment by charsbar** [comment]
Closed as this has already been merged and deployed in 2016.
