### ISSUE TITLE
no documentation of ADOPTME, NEEDHELP, HANDOFF

### ISSUE THREAD

**Issue by karenetheridge** [andk/pause#179]
https://pause.perl.org/pause/authenquery?ACTION=pause_04about doesn't contain any information about the new PAUSE ids used for indicating modules up for adoption -- as from the Lancaster consensus -- https://github.com/Perl-Toolchain-Gang/toolchain-site/blob/master/lancaster-consensus.md

NeilB also documented them here -- http://neilb.org/2013/08/07/adoptme.html

**Comment by neilb** [comment]
I think the canonical documentation for this is now the [PAUSE Operating Model](https://github.com/andk/pause/blob/master/doc/operating-model.md), so are we ok to close this ticket.

Or do we need more end-user-friendly documenting?

**Comment by charsbar** [comment]
> I think the canonical documentation for this is now the PAUSE Operating Model, so are we ok to close this ticket.

Yes, let's.

FYI:
ADOPTME: https://pause.perl.org/pause/query?ACTION=pause_operating_model#4_5_1_adoptme
HANDOFF: https://pause.perl.org/pause/query?ACTION=pause_operating_model#4_5_2_handoff
NEEDHELP: https://pause.perl.org/pause/query?ACTION=pause_operating_model#4_5_3_needhelp
