### ISSUE TITLE
Perl6 import of same named dist conflicts with Perl6 dist

### ISSUE THREAD

**Issue by jdv** [andk/pause#182]
A propsed set of fixes is in https://github.com/andk/pause/pull/181.
The alter script ran on my laptop in < 2mins.

**Comment by jdv** [comment]
Please hold off on looking at the proposed PR for a bit.  It only handles the http upload case.  Trying to decide if that's ok or if the PR needs to change to accommodate the http/ftp
fetching case as well.

**Comment by jdv** [comment]
OK.  Fixed, tested, and ready now.

**Comment by andk** [comment]
>>>>> On Sat, 05 Sep 2015 08:06:59 -0700, Justin DeVuyst <notifications@github.com> said:

  > OK. Fixed, tested, and ready now.

Are you saying that you changed the pull request today? I ask because I
do not see a change. When I look at
https://github.com/andk/pause/pull/181 then I see the last change from 

commit 0ff3163f17aedf00d3e551d839f0d62fae7e61e6
Author: Justin DeVuyst <justin@devuyst.com>
Date:   Thu Aug 27 11:40:07 2015 +0200

And in https://github.com/andk/pause/issues/182 I see no code on top of
it. Could you please clarify?

Thanks,
-- 
andreas

**Comment by jdv** [comment]
Andreas,

I force pushed the fix after rebasing it so I guess that's why it looks old.
Note the difference between the AuthorDate and CommitDate here:

https://gist.github.com/jdv/fab285e56fc45527897a

Also,  Here's the diff between the old fix and the new fix:

https://gist.github.com/anonymous/1d493158b82c784feb25

Thanks,
jdv

**Comment by andk** [comment]
>>>>> On Sun, 06 Sep 2015 16:24:12 -0700, Justin DeVuyst <notifications@github.com> said:

   > Andreas,
   > I force pushed the fix after rebasing it so I guess that's why it looks old.
   > Note the difference between the AuthorDate and CommitDate here:

   > https://gist.github.com/jdv/fab285e56fc45527897a

   > Also, Here's the diff between the old fix and the new fix:

   > https://gist.github.com/anonymous/1d493158b82c784feb25

   > Thanks,

Thanks for that, I should have used --pretty=fuller to get this
clarified immediately. Well, next time I know.

Unfortunately I have another question:

In the commit description of
https://github.com/jdv/pause/commit/0ff3163f17aedf00d3e551d839f0d62fae7e61e6
at the end of Point 3 I find "accordingly to useridbaseis_perl6 and uriis_per6"

I do not find anything similar to "uriis_per6" in the code. Is the
description wrong or something missing in the commits?

-- 
andreas

**Comment by jdv** [comment]
I had originally planned on doing that other index change but backed it out
in the code but forgot to remove it from the commit message.  Sorry.  I just
removed that bit from the message and force pushed again.

**Comment by andk** [comment]
>>>>> On Mon, 07 Sep 2015 00:25:44 -0700, Justin DeVuyst <notifications@github.com> said:

  > I had originally planned on doing that other index change but backed it out
  > in the code but forgot to remove it from the commit message. Sorry. I just
  > removed that bit from the message and force pushed again.

Thanks a lot, merged and deployed between 20:18 and 20:28 today.

Please let me know when something looks suspicious.

-- 
andreas
