### ISSUE TITLE
Link to upload via github URL explanation is dead

### ISSUE THREAD

**Issue by Relequestual** [andk/pause#183]
When uploading a module, there is the option to do so via a URL. There is then a comment that explains it can be done directy from a github repo...

"How to use this for direct publishing from your github repository has been described by Mike Schilli in his blog"

The link however (http://blog.usarundbrief.com/?p=36) is dead. Does anyone have a copy / want to write a new explanation which could be hosted here on github or as part of the FAQ?

**Comment by karenetheridge** [comment]
I don't like the idea of encouraging this practice. Part of a well-formed CPAN distribution are files that are auto-generated (e.g. by ExtUtils::MakeMaker) and are not normally included in a git repository.

**Comment by Relequestual** [comment]
I DID think it was a little bit odd! Although you COULD have a dist branch for that auto-generated, although I'm not sure this would be that well used. I haven't yet investigated into command line upload options, but I'm sure that's preferable.

Maybe the solution is to update the section in question with "how to do this via cli" information?

**Comment by GPHemsley** [comment]
Link is still present and still dead.

**Comment by dolmen** [comment]
@GPHemsley Directly uploading to CPAN from the source repo of a Perl project is still a bad idea. You would have to commit in your repo some files that are nowadays machine generated (MANIFEST, META.yml, META.json). Also some files which are in the repo should not be in the CPAN distribution (.gitignore, .travis.yml...).

**Comment by Relequestual** [comment]
@dolmen I had assumed you may have a build process and a release branch which would avoid those sorts of problems.

**Comment by charsbar** [comment]
re: #259

**Comment by charsbar** [comment]
The note on fetching a tarball from GitHub and the link in it are removed. Closing.
