### ISSUE TITLE
META6.json file detection is broken

### ISSUE THREAD

**Issue by jdv** [andk/pause#185]
The original code looks for the file in the root.  The proposed
fix allows for the file to be nested in the top level dir like a normal
cpan dist.  The proposed fix is in https://github.com/andk/pause/pull/184.

**Comment by jdv** [comment]
Please hold off on this for a bit as we don't have a consensus on the issue.

**Comment by jdv** [comment]
Nevermind.  I misread the spec.  Ready for review.

**Comment by jdv** [comment]
Has this been deployed?  I see that the PR was merged but am unsure about
how or if that relates to deployment.  I'm asking because my test just failed.

**Comment by andk** [comment]
>>>>> On Sun, 13 Sep 2015 07:51:54 -0700, Justin DeVuyst <notifications@github.com> said:

  > Has this been deployed? I see that the PR was merged but am unsure about
  > how or if that relates to deployment. I'm asking because my test just failed.

Sorry, I usually make a statement about deployment but forgot that
yesterday. Yes, it has been deployed. I did not restart anything, just
checked on the live server:

pause2:/home/puppet/pause# git describe --always
263fae8

The pull happened yesterday at:

2015-09-12 18:58  sudo -u puppet git pull

Time zone is UTC.

Let me know if I can provide any further insights.

-- 
andreas

**Comment by jdv** [comment]
Oops.  My local testing missed that $/ is set to "".  I've created the PR
and tested it much better this time:)  Its here:
https://github.com/andk/pause/pull/186.  Sorry about that.

Also,  why is $/ set to ""?

**Comment by andk** [comment]
>>>>> On Mon, 14 Sep 2015 00:29:54 -0700, Justin DeVuyst <notifications@github.com> said:

  > Oops. My local testing missed that $/ is set to "". I've created the PR
  > and tested it much better this time:) Its here:
  > #186. Sorry about that.

  > Also, why is $/ set to ""?

OMG, that's older than the SVN repo. I fear I can't dig that out any more:(

-- 
andreas

**Comment by jdv** [comment]
Confirmed fixed.  Thanks.
