### ISSUE TITLE
incorrect maintainer identified in error message

### ISSUE THREAD

**Issue by karenetheridge** [andk/pause#188]
I just uploaded an older version of `if` (knowing full well that it won't be indexed), and I got this reply back:

```
Status: Permission missing
==========================

     module : if
     version: 0.0605
     in file: if-0.0605/if.pm
     status : Not indexed because permission missing. Current registered
             primary maintainer is FGLOCK. Hint: you can always find the
             legitimate maintainer(s) on PAUSE under "View Permissions".
```

Um, no, FGLOCK owns `If`, not `if`. The maintainer of `if` should have been identified as ILYAZ.

Presumably this is due to `If` coming first in the permissions file and a case-insensitive search was done.

```
If,FGLOCK,f
if,ILYAZ,c
if,P5P,f
```

**Comment by dagolden** [comment]
No, IYLAZ is a co-maintainer.  P5P (a group) is primary on "if".  It's possible the reported maintainer is whichever the (case insensitive) SQL query returns first -- as any conflict is sufficient to prevent indexing.

I do wish we would go clean up all these ambiguities, even if that means semi-arbitrarily dropping one side of the case conflicts.  :-/

**Comment by rjbs** [comment]
The data have been fixed since this issue.
