### ISSUE TITLE
META6.json version field validation incorrect so removing

### ISSUE THREAD

**Issue by jdv** [andk/pause#194]
See https://github.com/andk/pause/pull/193.

**Comment by andk** [comment]
While applying 193 I discovered that 15a94f96be3d4a35401520fcac2a03a4108d8fb7 broke the test t/mldistwatch-misc.t. Could you have a look?

``` text
commit 15a94f96be3d4a35401520fcac2a03a4108d8fb7
Author: Justin DeVuyst <justin@devuyst.com>
Date:   Tue Sep 8 14:14:23 2015 +0200

    Fix regex for META6.json detection.
```

Thanks!

**Comment by andk** [comment]
Now fixed with acbba53.

**Comment by jdv** [comment]
It apears that you basically reverted my changes because of the automated test failures.  The
problem with that is the automated test is wrong.  Please revert acbba53.  Although I forgot to update
the automated test I did test both commits manually and they were ok.

1.  Having a META6.json in the root of the tarball is invalid - hence the requirement of a preceding slash.
2.  It is invalid for the version field in META6.json to be required to start with a v and digits.  Which is exactly why this bug report and PR were created.

**Comment by andk** [comment]
>>>>> On Wed, 23 Dec 2015 14:55:20 -0800, Justin DeVuyst <notifications@github.com> said:

  > It apears that you basically reverted my changes because of the
  > automated test failures. The
  > problem with that is the automated test is wrong. Please revert
  > acbba53. Although I forgot to update
  > the automated test I did test both commits manually and they were ok.

  > 1 Having a META6.json in the root of the tarball is invalid - hence
  >   the requirement of a preceding slash. 
  > 2 It is invalid for the version field in META6.json to be required to
  >   start with a v and digits. Which is exactly why this bug report and
  >   PR were created. 

Oops. Sorry. Yes, I revert, I apparently garbled things up. But somebody
has to fix t/mldistwatch-misc.t which is broken since September. Can
you, please?

-- 
andreas

**Comment by jdv** [comment]
Thanks!  I just did - https://github.com/andk/pause/issues/197.
