### ISSUE TITLE
length of versions does not match the architecture

### ISSUE THREAD

**Issue by karenetheridge** [andk/pause#203]
My latest upload of Acme::Pi failed:

```
The following report has been written by the PAUSE namespace indexer.
Please contact modules@perl.org if there are any open questions.

  User: ETHER (Karen Etheridge)
  Distribution file: Acme-Pi-3.14159.tar.gz
  Number of files: 32
  *.pm files: 3
  README: Acme-Pi-3.14159/README
  META-File: Acme-Pi-3.14159/META.json
  META-Parser: Parse::CPAN::Meta 1.4414
  META-driven index: no
  Timestamp of file: Mon Mar 14 07:32:18 2016 UTC
  Time of this run: Mon Mar 14 07:33:50 2016 UTC

Status of this distro: Version string exceeds maximum allowed length of 16b
===========================================================================

The following packages (grouped by status) have been found in the distro:

Status: Version string exceeds maximum allowed length of 16b
============================================================

     module : Acme::Pi
     version: 3.14159265358979324
     in file: Acme-Pi-3.14159/lib/Acme/Pi.pm
     status : Version string exceeds maximum allowed length of 16b

__END__
```

I have not changed the $VERSION since previous uploads, which have indexed successfully.

I wonder if this is related to this issue I saw go by on p5p?  What version of perl is PAUSE running? https://rt.perl.org/Ticket/Display.html?id=127182

Or could the issue be in version.pm? What version of that is PAUSE running?

**Comment by karenetheridge** [comment]
Note the actual version in the code is not 3.14159, but rather:

    my $version = atan2(1,1) * 4; $Acme::Pi::VERSION = "$version";

...which on its first release revealed issues with PAUSE's version extraction, but were fixed in Lyon (QAH 2014).

**Comment by karenetheridge** [comment]
ilmari++ -- looks like I'm hitting https://github.com/andk/pause/pull/195.

I'll do a `$version = substr($version, 0, 16)`.

**Comment by karenetheridge** [comment]
[@Author::ETHER/UploadToCPAN] POSTing upload for Acme-Pi-3.141592.tar.gz to https://pause.perl.org/pause/authenquery

**Comment by karenetheridge** [comment]
```
Status: Successfully indexed
============================

     module : Acme::Pi
     version: 3.14159265358979
     in file: Acme-Pi-3.141592/lib/Acme/Pi.pm
     status : indexed
```

Thank you all for playing along from home.

**Comment by andk** [comment]
>>>>> On Mon, 14 Mar 2016 10:50:39 -0700, Karen Etheridge <notifications@github.com> said:

  > I wonder if this is related to this issue I saw go by on p5p? What
  > version of perl is PAUSE running?

% /opt/perl/current/bin/perl -v            

This is perl 5, version 16, subversion 2 (v5.16.2) built for x86_64-linux-ld

  > Or could the issue be in version.pm? What version of that is PAUSE
  > running?

% /opt/perl/current/bin/perl -MV=version
version
        /opt/perl/v5.16.2/165a/lib/site_perl/5.16.2/x86_64-linux-ld/version.pm: 0.9909
        /opt/perl/v5.16.2/165a/lib/5.16.2/version.pm: 0.99

Looks like an upgrade would be something for the QAH.

-- 
andreas
