### ISSUE TITLE
CPAN Uploads failing

### ISSUE THREAD

**Issue by karenetheridge** [andk/pause#205]
Using CPAN::Uploader (used by the 'cpan-upload' script, and Dist::Zilla), uploads are failing:

```
: [ether@jaeger git/Moose]$; cpan-upload Moose-2.1703-TRIAL.tar.gz
registering upload with PAUSE web server
POSTing upload for Moose-2.1703-TRIAL.tar.gz to https://pause.perl.org/pause/authenquery
request failed with error code 406
  Message: Not Acceptable
```

However, submitting the tarball at https://pause.perl.org/pause/authenquery?ACTION=add_uri did work.

**Comment by andk** [comment]
>>>>> On Tue, 12 Apr 2016 16:43:54 -0700, Karen Etheridge <notifications@github.com> said:

  > Using CPAN::Uploader (used by the 'cpan-upload' script, and
  > Dist::Zilla), uploads are failing:

  > : [ether@jaeger git/Moose]$; cpan-upload Moose-2.1703-TRIAL.tar.gz
  > registering upload with PAUSE web server
  > POSTing upload for Moose-2.1703-TRIAL.tar.gz to https://pause.perl.org/pause/authenquery
  > request failed with error code 406
  >   Message: Not Acceptable

  > However, submitting the tarball at
  > https://pause.perl.org/pause/authenquery?ACTION=add_uri did work.

Please retry.

I was experimenting with SET tx_isolation = 'READ-COMMITTED' but
reverted the change due an incompatibility with binary logging.

Thanks for the quick report!

Sorry for the inconvenience,
-- 
andreas

**Comment by andk** [comment]
Apparently it was the mentioned database misconfiguration
