### ISSUE TITLE
pause.cpan.org now has pause.perl.orgs cert (cert fail)

### ISSUE THREAD

**Issue by exodist** [andk/pause#213]
I tried to log into pause.cpan.org and got a certificate warning due to it using the pause.perl.org certificate. This issue is new as of this evening.

**Comment by andk** [comment]
Do you have problems when you connect to pause.perl.org instead?

**Comment by exodist** [comment]
Nope. Pause.perl.org works fine.

**Comment by charsbar** [comment]
For information, the problem was that previously pause url was explicitly built with ServerName set in the apache.conf, but we had nothing like that after we switched to Plack. I proposed to set it in PrivatePAUSE.pm, and use it explicitly, instead of HTTP_HOST (or the equivalent from the proxy).

**Comment by andk** [comment]
#214 fixed it and is applied, closing. Thanks, Chad, well spotted!
