### ISSUE TITLE
users should not be able to drop firstcome without a replacement user

### ISSUE THREAD

**Issue by karenetheridge** [andk/pause#229]
It looks like an author can drop firstcome permissions on a module and leave the module ownerless, even if there are other users with comaint permissions still -- for example Business::PaperlessTrans::Client.

If a user drops firstcome and doesn't appoint a successor, then ownership should pass to a placeholder user such as ADOPTME.

(I would also suggest that all existing modules in the database that have 'c' permissions but no 'f' be given an 'f' entry to ADOPTME, or perhaps a new user such as UNKNOWN.)

**Comment by charsbar** [comment]
With #328, giving up primary permissions transfers their permissions to ADOPTME. If this is inconvenient, please open a new issue (and maybe refer to this). I'm closing this for now.
