### ISSUE TITLE
Show the GPG Public Key on About page

### ISSUE THREAD

**Issue by dolmen** [andk/pause#243]
The GPG public key of the PAUSE server is a major information to validate CHECKSUMS files when downloading files from CPAN. But the key is hard to find. The *About* page doesn't talk about it. The *PAUSE News* page has a non-working [indirect link](http://keyserver.veridis.com:11371/pks/lookup?template=netensearch%2Cnetennomatch%2Cnetenerror&search=pause%40pause.perl.org&op=index&fingerprint=on&submit=Get+List) and I've not found a single place where even the key id is listed.

I suggest to add the GPG public key in PEM format on the *About* page.

**Comment by andk** [comment]
Thanks for the idea, highly appreciated. My own key was already quite old, so I updated it at the  same time. Closing issue.
