### ISSUE TITLE
CHECKSUMS files are not signed with the same signature

### ISSUE THREAD

**Issue by dolmen** [andk/pause#244]
The CHECKSUMS file at the root of CPAN does seem to have been signed with a different GPG key than more recent CHECKSUMS files.
Compare the signature of those files:
https://cpan.metacpan.org/authors/id/CHECKSUMS
https://cpan.metacpan.org/authors/id/D/DO/CHECKSUMS

**Comment by dolmen** [comment]
Cc: @PerlToolchainGang

**Comment by andk** [comment]
What exactly are you observing that looks wrong? While I'm surprised that we have CHECKSUMS files that are 9 years old, I don't think it's wrong. So what do you see that looks wrong?

**Comment by dolmen** [comment]
The `/authors/id/CHECKSUMS` lists the subdirectories of `/authors/id`. If it is 9 years old, does that mean that it has not been updated for 9 years and that I will not find recently created PAUSE authors in that file?

I'm writing a CPAN download library in Go that check the signatures of CHECKSUMS files (see [dolmen-go/CPAN](/dolmen-go/CPAN)) and I was expecting that a single public key was necessary to check the signature of any CHECKSUMS file. This problem shows this is currently a wrong assumption. So I will have to update my library to allow multiple PAUSE key. But I don't know this key and this seems wrong from a security perspective: why would multiple keys be necessary?

So a simpler and better fix would be on PAUSE side to update the root CHECKSUMS file and re-sign it with the latest key. Is there any reason to not do that? Is is because the root CHECKSUMS is never automatically updated?

Note that I have only checked the CHECKSUMS file I have available on my machine as downloaded by CPAN::Mini setup to only download a subset of CPAN. The PAUSE server *may* contain other CHECKSUMS file with old singatures.

**Comment by dolmen** [comment]
There is also another issue: `authors/id/CHECKSUMS` contains old entries for symlinks that do not exist anymore on mirrors or even on backpan.perl.org.

**Comment by andk** [comment]
>>>>> On Wed, 14 Jun 2017 09:03:31 -0700, Olivier Mengué <notifications@github.com> said:

  > The /authors/id/CHECKSUMS lists the subdirectories of /authors/id. If
  > it is 9 years old, does that mean that it has not been updated for 9
  > years and that I will not find recently created PAUSE authors in that
  > file?

Ah, now we come closer. It contains 26 capital letter subdirectories for
each letter of the alphabet, so we will not get more. Symlinks are not
supported anymore.

We can change the algorithm to remove entries of deleted symlinks, they
are a distraction that nobody needs. I have not checked, but I suppose
*if* we would add one single file or directory to the root directory,
the symlinks in the root CHECKSUMS file would disappear. But this would
not happen so easily in the root directory.

  > I'm writing a CPAN download library in Go that check the signatures of
  > CHECKSUMS files (see dolmen-go/CPAN) and I was expecting that a single
  > public key was necessary to check the signature of any CHECKSUMS file.
  > This problem shows this is currently a wrong assumption. So I will
  > have to update my library to allow multiple PAUSE key. But I don't
  > know this key and this seems wrong from a security perspective: why
  > would multiple keys be necessary?

That seems to be how PGP/gnupg works. A key is always a bundle of keys.
Try it with 'gpg --verify'. I have no understanding of the inner
workings of PGP/gnupg except for what we are doing here.

  > So a simpler and better fix would be on PAUSE side to update the root
  > CHECKSUMS file and re-sign it with the latest key. Is there any reason
  > to not do that? Is is because the root CHECKSUMS is never
  > automatically updated?

(1) it would generate extra traffic without a need

(2) no, the age of he root CHECKSUMS file is not a political decision,
it just is a side effect of how the algorithm works so far.

  > Note that I have only checked the CHECKSUMS file I have available on
  > my machine as downloaded by CPAN::Mini setup to only download a subset
  > of CPAN. The PAUSE server may contain other CHECKSUMS file with old
  > singatures.

Not many due to steady changes in most directories, but there are. Here
is the age distribution:

% find /home/ftp/pub/PAUSE/authors/id -name "CHECKSUMS" | perl -nle 'use File::stat;  $|=1;my $mtime = stat($_)->mtime; $mtime /= 10000000; print 10000000 * int $mtime' | sort | uniq -c|sort -k 2 -n 
      2 1140000000
      3 1160000000
      1 1170000000
     11 1180000000
     39 1190000000
     17 1200000000
      9 1210000000
     15 1220000000
     13 1230000000
     17 1240000000
     31 1250000000
     15 1260000000
      5 1270000000
      2 1280000000
     11 1290000000
     13 1300000000
      8 1310000000
     16 1320000000
     14 1330000000
      6 1340000000
     21 1350000000
     16 1360000000
     18 1370000000
     23 1380000000
     24 1390000000
     18 1400000000
     14 1410000000
     25 1420000000
     18 1430000000
     17 1440000000
      9 1450000000
     29 1460000000
     16 1470000000
     15 1480000000
   8679 1490000000


-- 
andreas

**Comment by dolmen** [comment]
After digging more in OpenPGP and the Go API I have now fixed most issues in my Go code, in particular to use the PAUSE key file as a keyring instead of extracting only the first public key.

The pain points:
- the Go API isn't able to easily read the PAUSE key because of unimplemented features (see golang/go#20686), so I had to implement a workaround 
- the root CHECKSUMS is signed in OpenPGP signature version 3 style (which requires special handling with the Go API) while more recent file use V4
- the root CHECKSUMS file refers to a RECENT-2d.yaml file (which by the way has not been updated since 2008) with a `size` property defined as a string while other CHECKSUMS files expose it as an int.

So I would welcome:
- the removal of `/authors/id/RECENT-2d.yaml`
- the update of `/authors/id/CHECKSUMS` removing `RECENT-2d.yaml` and all inexistent symlinks, and resigned with a V4 signature
But I will probably handle `/authors/id/CHECKSUMS` specifically anyway (ignoring it completely).

**Comment by andk** [comment]
There were two bugs: the root directory was never updated (it seems to have been checksummed manually, cannot remember) and the config variable MIN_MTIME_CHECKSUMS was misconfigured. Fixed both at once in commit 442822c.

Thanks for the analysis!

**Comment by dolmen** [comment]
I'm glad I finally did not totally waste your time as there was a real bug under!

**Comment by andk** [comment]
>>>>> On Sun, 18 Jun 2017 15:28:24 -0700, Olivier Mengué <notifications@github.com> said:

  > I'm glad I finally did not totally waste your time as there was a real
  > bug under!

;) Thanks again!

-- 
andreas
