### ISSUE TITLE
Change Permissions interface for admins incomplete

### ISSUE THREAD

**Issue by andk** [andk/pause#249]
06perms.txt has the line

```
Sane,RATCLIFFE,c
```

When using the web interface:

- as admin via "Select User/Action"
- then selecting user "RATCLIFFE" and the "Change Permissions" pull down

then the section "4. You are co-maintainer" is empty.

Expected: section 4 should contain the namespace "Sane".

**Comment by charsbar** [comment]
Andreas, https://github.com/andk/pause/pull/241 should address this. Could you review and merge it if it's ok?

**Comment by neilb** [comment]
@andk ping on @charsbar's comment above. I don't know the context of the change to comment, but it would be smashing if it fixed the issue with Sane.

**Comment by neilb** [comment]
@andk @charsbar - any chance you two could sit down together on this issue at the PTS please, and see whether #241 does fix it, and can be deployed?

The project to get rid of all case-conflicting permissions can't be completed until this issue (and another one) have been resolved.

You'll make at least one person very happy ;-)

**Comment by charsbar** [comment]
This should have already been fixed (re #241).
