### ISSUE TITLE
The NOTRANSFER permission introduced in the POM likely unusable

### ISSUE THREAD

**Issue by ribasushi** [andk/pause#256]
I attempted to give comaint to the newly codified [`NOTRANSFER` user](https://github.com/andk/pause/blob/master/doc/operating-model.md#454-notransfer). I hit a problem immediately within the UI, as the input box is limited to 9 characters ( the global PAUSE id limit afaik ), whereas `NOTRANSFER` is 10 characters long. I assume the user hasn't been created either: https://metacpan.org/author/NOTRANSFER

I suspect the fastest way to remedy this would be to create the user `NOXFER`, and change the POM to reflect the new name.

Thanks!

**Comment by andk** [comment]
I agree. Thanks for doing the frst reality testing on the paper.

Unless somebody vetoes in the next hour I'll follow your NOXFER suggestion

**Comment by andk** [comment]
Done, NOXFER is it now.

Thanks again for sterling diagnostic and therapeutic heads up.
