### ISSUE TITLE
Documentation of how to upload to PAUSE from a GitHub repo tarball URL

### ISSUE THREAD

**Issue by ap** [andk/pause#259]
Regarding fcee050d60cf54ca48de1df4e11f698dc70ed519 – the contents of the dead link are archived at
https://web.archive.org/web/20111202165941/http://blog.usarundbrief.com:80/?p=36

However, the URLs in it are old. Following the instructions there will still work, but instead of `.../tarball`, GitHub itself now uses `.../releases` for the tag list page and `.../archive/...` for the download link. So the example URL should now be
[https://github.com/mschilli/proc-simple-perl/__*archive*__/rel_131/Proc-Simple-1.31.tar.gz](https://github.com/mschilli/proc-simple-perl/archive/rel_131/Proc-Simple-1.31.tar.gz).

I think it makes sense to upstream this into CPAN’s own docs somewhere instead of linking Mike’s dated (if not outdated) blog post forever more.

**Comment by charsbar** [comment]
Due to Dist::Zilla and its friends, people tend to keep less files in their repository than before. So just changing the URL to .../archive/... may not always work. IMHO it makes more sense to remove those sentenses, or even add some extra check to prevent inappropriate upload if it comes directly from GitHub.

**Comment by karenetheridge** [comment]
We could require the presence of at least one of: META.yml, META.json,
Makefile.PL, Build.PL (which contain nearly-required information such as
author, licence, and prerequisites) in the uploaded distribution in order
for it to be indexed by PAUSE.

**Comment by charsbar** [comment]
@karenetheridge META.yml and META.json are good enough when you create a distribution by Dist::Zilla etc, but are they really enough for all the current CPAN clients to configure/build/install it?

**Comment by karenetheridge** [comment]
Are you saying this is too much, or not enough? We don't require a Makefile.PL today, in order for a distribution to be indexed.

**Comment by charsbar** [comment]
@karenetheridge We don't require Makefile.PL/Build.PL for a distribution to be indexed, but I doubt all the current CPAN client can install a distribution that doesn't have Makefile.PL/Build.PL (some can, and it'd be nice if all would be able to do that eventually, though). So I asked you if it's really good for PAUSE to have such a distribution.

**Comment by ap** [comment]
> Due to Dist::Zilla and its friends, people tend to keep less files in their repository than before. So just changing the URL to .../archive/... may not always work.

Sure, not always. Maybe even rarely nowadays. So what, though? For https://github.com/mschilli/proc-simple-perl it still works. Not everyone uses the same tooling.

> MHO it makes more sense to remove those sentenses

I’d just mention the caveat that this will only do what you wanted if the resulting tarball is a full dist. That part of your objection I completely agree with; that’s a good point.

> or even add some extra check to prevent inappropriate upload if it comes directly from GitHub.

No. PAUSE allows authors to upload any file they want. The place for policy is in the indexer.

**Comment by karenetheridge** [comment]
> No. PAUSE allows authors to upload any file they want. The place for policy is in the indexer.

Agreed -- Andreas has been very clear about this as well. PAUSE will not limit uploads from any registered user.

What we can do is try to detect possibly-erroneous uploads and inform the user in the email receipt. e.g. "This appears to be missing some important files. Did you upload from GitHub? Read here for how to do this correctly: <link>"

**Comment by ap** [comment]
> I’d just mention the caveat that this will only do what you wanted if the resulting tarball is a full dist. That part of your objection I completely agree with; it’s a good catch, that a lot of people nowadays can’t use this.

Thinking about this further:

People who use Dist::Zilla almost certainly don’t use the PAUSE web interface to upload their releases – they just say `dzil release`. It seems to me that the people who would be most interested in being able to paste a GitHub URL into the PAUSE upload form are the people who are not using any post-MakeMaker authoring tool, i.e. the people whose repos most likely directly look like a CPAN dist tarball. People who use authoring tools and cannot do this probably all have more convenient ways of putting releases on CPAN than the PAUSE web interface.

This doesn’t change the fact that I would add a caveat, but I now think it’s not necessary to go into the issue at length. (Like, just starting the sentence with “If your repository contains all of the contents of a proper CPAN distribution, you can [etc]” seems enough.)

**Comment by charsbar** [comment]
>People who use Dist::Zilla almost certainly don’t use the PAUSE web interface to upload their releases – they just say dzil release. It seems to me that the people who would be most interested in being able to paste a GitHub URL into the PAUSE upload form are the people who are not using any post-MakeMaker authoring tool, i.e. the people whose repos most likely actually look like a CPAN dist tarball. People who use authoring toolchains (and therefore cannot use their repo contents directly as a CPAN dist tarball) probably all have more convenient ways of putting releases on CPAN than the PAUSE web interface.

I still don't think it a good idea to explain how to upload via GitHub, because it's still more error prone (broken/stale META files etc) than uploading a distribution made by ```make dist``` (or whatever), but your explanation makes me feel less worried :)

**Comment by charsbar** [comment]
The note on fetching a tarball from GitHub and the link in it are removed. Closing.
