### ISSUE TITLE
Cannot use email with dots

### ISSUE THREAD

**Issue by xsawyerx** [andk/pause#260]
Editing the email ("secret email," if it matters) is considered invalid if it contains dots.

**Comment by charsbar** [comment]
@xsawyerx, could you show us exactly what email address (local part) you used? Or, PAUSE uses Email::Address::addr_spec to validate an email address, so you can use it to see if it's really valid (or broken but commonly used).

**Comment by xsawyerx** [comment]
Whoops!

I misread. It's the public one. I think this is a duplicate of #139. Sorry for the false positive.
