### ISSUE TITLE
Pagination issues in new PAUSE

### ISSUE THREAD

**Issue by haarg** [andk/pause#277]
In the new PAUSE, there are some issues with the pagination.

  * No indication of the page.  When you click to switch paging, nothing indicates which page you are on.  The page is not in the URL, nor do the pagination links change visually in any way.
  * The scrolling stays at the same place when switching paging.  The pages are sorted and intended to be read from top to bottom, so when you switch pages the natural thing is to start reading at the top.  When you click on a new page at the bottom of the page, the scroll position stays at the bottom of the page.  So you have to manually scroll back to the top to continue reading normally.
  * The pagination in general seems rather useless.  If the markup was more complex or had dynamic elements it would make more sense.  The markup for the full list is delivered to the client, so the paging makes no difference in the fetch time.  Even with thousands of entries in table, the render time is extremely short.  Pagination seems to add extra complexity with nearly no gain.

**Comment by leonerd** [comment]
Additionally, because it doesn't interact with the URL it plays very badly with browser "Back" button. If you use "Back" you don't go back to the previous page of pagination, you jump further back in the browser's history than you might expect.

**Comment by leonerd** [comment]
Additionally, if you Ctrl-R to refresh you're now back on page 1, regardless of which page you had previously been looking at

**Comment by charsbar** [comment]
Pagination stuff is gone.
