### ISSUE TITLE
Permissions pages not linkable

### ISSUE THREAD

**Issue by haarg** [andk/pause#278]
When checking the permissions on a module, the form submits using POST.  It also only accepts POST requests.  Given that it is a read only operation, it would be better if it was a GET.  Using POST means that the result pages can't be linked to, which is useful both for sharing and for accessing directly by modifying a URL.

I assume this applies to other pages, but haven't checked.  Any read only operations should be using GET, not POST.

**Comment by charsbar** [comment]
This has already been fixed for a while.
