### ISSUE TITLE
Inconsistent "normalization" of versions

### ISSUE THREAD

**Issue by Grinnz** [andk/pause#279]
It appears that versions like '0.001.0' are normalized to '0.001' by the following code: https://github.com/andk/pause/blob/bae8c4c38136078752c1284c087154bd377a575e/lib/PAUSE/pmfile.pm#L521-L580

Example result from 02.packages.details.txt:

    Acme::PERLANCAR::Test::Versioning 0.001  P/PE/PERLANCAR/Acme-PERLANCAR-Test-Versioning-0.001.00.0.0.tar.gz

The only indication for the purpose of this is the comment saying "the trailing zeroes would cause unnecessary havoc". However, a similar version '0.1.0' or '0.01.0' would be left intact, because they aren't numerically equivalent to the decimal versions they look like. All of these are completely valid version tuples including '0.001.0', so what is the purpose of this normalization?

**Comment by rjbs** [comment]
I'm afraid I don't know.  While I think this code is a bit of a mess, I'm very reticent to change it too much without a pretty comprehensive set of tests or rules.  I'm closing this issue because I don't think there's a clear next step, but let me know if you believe otherwise.
