### ISSUE TITLE
When admin looks at someone else's account info, it refers to the wrong email address

### ISSUE THREAD

**Issue by neilb** [andk/pause#280]
When an admin looks at the account info for another user, the box about email forwarding mentions the PAUSE admin's CPAN email address, instead of the address of the account they're looking at.

    The email address USER@cpan.org should be configured to forward email to ...

Here **USER** should be the PAUSE id of the user I'm looking add, but instead it is **neilb**.

I'm trying to change the radio button from "neither nor" to "my secret email address", for another user, but it's not working. Dunno if it's due to the issue described above, or if that's a separate issue.

**Comment by charsbar** [comment]
This should have been fixed already. If not please reopen.
