### ISSUE TITLE
Make an easy "Put Up My Module(s) For Adoption" button

### ISSUE THREAD

**Issue by plicease** [andk/pause#291]
How about an easy button or menu that allows you to put modules up for adoption from within the PAUSE web interface?

I was conversing with Peter Billam about handing over `Term-Clui` for me to maintain, which he was happy to do, and he mentioned that he had trouble finding a button to easily put up his other modules for adoption.  I mentioned the ADOPTME PAUSE id could be used for this purpose, but that is pretty arcane which is probably why he didn't know about that practice.  The button or interface above could simply be an interface for adding ADOPTME to co-maint.

**Comment by rjbs** [comment]
Meantime this exists: https://metacpan.org/dist/App-PAUSE-Comaint/view/script/comaint
