### ISSUE TITLE
form to request PAUSE account has misleading full name help text

### ISSUE THREAD

**Issue by tmetro** [andk/pause#293]
The form:
https://pause.perl.org/pause/query?ACTION=request_id

under the "full name" field helpfully adds:
>... This field is considered to be filled with both names, separated by a space. ...

pretty strongly implying that only "x y" format is accepted. But in actuality it can handle multiple words, and even some punctuation, like commas.

The help text should be updated to accurately reflect what is the acceptable format.

**Comment by charsbar** [comment]
Look at the actual code: https://github.com/charsbar/pause/blob/mojo_wip/lib/pause_2017/PAUSE/Web/Controller/Public/RequestId.pm#L55

or the code in the past:
https://github.com/andk/pause/blob/master/lib/pause_1999/edit.pm#L2876

and the commit that mattered: https://github.com/andk/pause/commit/4c11985a38485e4890e2d09bbd576df3a5797ccc

It really expects only a white space in the field, to exclude a spam entry as clearly stated in the note (since 2012; people registered before may have no white space in their fullname, like GUGOD (劉康民). See https://metacpan.org/author/GUGOD ).

Do you still think we need to add some extra note?

**Comment by Grinnz** [comment]
It could simply say "multiple" names instead of "both".

**Comment by ap** [comment]
That would suggest it’s referring to multiple names, which isn’t true. It’s referring to all parts of the name.

**Comment by Grinnz** [comment]
"both" already suggests that except that it's referring to the "first name" and "last name" mentioned earlier, but "all parts of the name, separated by spaces" works for me.

**Comment by ap** [comment]
@charsbar:

> Look at the actual code:

I believe that was his point: the code does one thing, but the documentation suggests another thing.

This problem still exists. The current form template `lib/pause_2017/templates/public/request_id/_form.html.ep` [as it exists in `master` today](/andk/pause/blob/bdee8c594e8d84d4d934c9fd2682d5eb5656545b/lib/pause_2017/templates/public/request_id/_form.html.ep) contains this explanatory note:

> Note: PAUSE has been developed in a time when it was more common than today that people have names consisting of at least a first name and a second name, like <i>Ben Cartwright</i> or <i>Tony Nelson</i>, you get the idea. This field is considered to be filled with both names, separated by a space. This trivial expectation was then coded into the server side sanity check of this form and it turned out to be a super efficient spam protection because bots often did not try to enter a space in the middle of the field. It was about the year 2003 when people started to complain that they had tried <i>Peter</i> and it did not work. Poor Peter, please remember you <b>do</b> have a second name.

Note that the “both names” text is still there. And it still doesn’t tell the user what exactly the code expects.

But also… I am willing to bet money that the last sentence was written by Andreas, in which case I can exactly imagine the good-natured, slightly mischievous, apologetic tone implied (and I am quite amused by it 🙂) – but I also believe that without the context of having met him, the tone of this text will read as condescending / patronising to users. 🙁

@andk: Maybe something like this?

> Note: You can enter fairly free-form text here but it must consist of at least two space-separated words. This is a spam protection measure we discovered accidentally. Back when PAUSE was developed in the nineties, people would generally fill out a field asking for a full name with a first name and a second name, like <i>Ben Cartwright</i> or <i>Tony Nelson</i>. When this trivial expectation was coded into the server as a sanity check, it turned out to block many spam bots because they often did not try to enter a space in the middle of the field. It was only around 2003 that people started complaining that they had tried <i>Peter</i> and it did not work. Apologies for insisting, Peter – but feel free to make something up to satisfy the requirement.

**Comment by karenetheridge** [comment]
obligatory link :)  https://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/

**Comment by andk** [comment]
@ap: thanks for the suggestion, I like it.

**Comment by charsbar** [comment]
Thanks.
