### ISSUE TITLE
The PAUSE indexer was not able to parse

### ISSUE THREAD

**Issue by zdm** [andk/pause#297]
Hi,

I am constantly get the following error from the PAUSE indexer:
```
module : Pcore::HTTP::Server
version: undef
in file: Pcore-v0.71.1/lib/Pcore/HTTP/Server.pm
status : The PAUSE indexer was not able to parse the following line
in that file: C< has server_tokens => "Pcore-HTTP-Server/$Pcore::VERSION";
```
This string should be processed in run-time, why indexer trying to parse it?

Also I have the same string in the other module from this distribution and PAUSE indexer parse it without errors.

How I can avoid this?

Thank you.

**Comment by karenetheridge** [comment]
> This string should be processed in run-time, why indexer trying to parse it?

The indexer parses perl modules, line by line, looking for things that look like a `$VERSION` declaration. That's how a module's version is determined.  The exact mechanism is captured in this module: https://metacpan.org/pod/Parse::PMFile

The parser is finding that line of code because there is no earlier `$VERSION` declaration in the file. I would recommend adding `$VERSION` declarations to all your .pm files in any case, so one can see which version of a module one has installed -- and adding one to this file would avoid the PAUSE error.

**Comment by zdm** [comment]
Hmm.
Parser works absolutely incorrectly.
This code `"Pcore-HTTP-Server/$Pcore::VERSION";` is not looks like $VERSION. This is even not assignment.
I think, that parser must try to find only `$VERSION\s*=\s*[\d.]+;`

**Comment by charsbar** [comment]
@zdm, there is an old PR to fix this issue ( https://github.com/andk/pause/pull/70/files ), which I was so lazy that I hadn't added a test nor asked Andreas to merge it. It looks like both Andreas and I are going to attend TPC in Glasgow next week, so I'll try to find some time to update the PR and asked him to merge it.

@karenetheridge, it's a PAUSE bug that thinks ```$Pcore::VERSION];    # ( is => 'ro', isa => Maybe [Str] ); ``` is a version declaration, which is obviously not, and there are many variations of this example. I think it's better to fix the parser (Parse::PMFile has already been fixed). Adding ```$VERSION = 'some version number';``` at the top of all modules is surely a workaround for this issue, but as Pcore has a lot of modules to fix, you'll probably need to convince him to use Dist::Zilla first ;)

**Comment by zdm** [comment]
I am using distribution version and don't want to patch all modules during release, this has no sense in my case.
Thank you, I will waiting for the fix.

**Comment by ap** [comment]
@zdm: CPAN dependency resolution works most reliably when every file in a distribution has a `$VERSION` and it’s the same version in all files, so there is a good reason to do that. But you shouldn’t have to do it just to make this bug go away.

@charsbar: Just please be careful not to make the parser stricter unnecessarily while you’re making it smarter. I’m wondering if there’s a good way to build up a nice huge batch of test cases… maybe pull down as much of BackPAN as possible, put every module through Parse::PMFile, and then go through all the cases where it threw “not able to parse the following line” and try to make them go away without reducing the set of successful parses? It would also be nice to be able to compare against its historical outputs, but unfortunately the index history only goes back a few years… 😐

**Comment by karenetheridge** [comment]
> I am using distribution version and don't want to patch all modules during release

There is another alternative -- make use of the 'provides' field in metadata. When 'provides' is populated, PAUSE does not need to parse every .pm file for a `$VERSION` declaration.

https://metacpan.org/pod/CPAN::Meta::Spec#provides

**Comment by zdm** [comment]
This is a good advice, I will use it, thank you.
