### ISSUE TITLE
Converting a module to semver

### ISSUE THREAD

**Issue by geofffranks** [andk/pause#299]
I'm trying to convert the versioning of [a module](https://github.com/geofffranks/test-mockmodule) to semver, but when I upload version 0.17.0 to PAUSE, the indexer complains that it's a lower version than 0.16. I would have thought the would treat 0.16 as 0.16.0 for the comparison (or even 0.0.16), but in both cases the old version would still be lower than 0.17.0.

Is there any documentation on how to make this transition successfully?

**Comment by andk** [comment]
>>>>> On Fri, 31 Aug 2018 21:18:06 -0700, Geoff Franks <notifications@github.com> said:

  > I'm trying to convert the versioning of a module to semver, but when I
  > upload version 0.17.0 to PAUSE, the indexer complains that it's a
  > lower version than 0.16. I would have thought the would treat 0.16 as
  > 0.16.0 for the comparison (or even 0.0.16), but in both cases the old
  > version would still be lower than 0.17.0.

  > Is there any documentation on how to make this transition
  > successfully?

The core documentation on how v-strings work is in `man perldata` under
the topic `Version Strings`.

Also helpful the test t/op/ver.t:

 : my $vs = v1.20.300.4000;
 : is($vs,"\x{1}\x{14}\x{12c}\x{fa0}","v-string ne \\x{}");
 : is($vs,chr(1).chr(20).chr(300).chr(4000),"v-string ne chr()");

I also like David Golden's article
http://www.dagolden.com/index.php/369/version-numbers-should-be-boring/

Let me know if you need more help.

Regards,
-- 
andreas

**Comment by geofffranks** [comment]
Thanks! David Golden's article set me straight. I wanted `0.170.0` not `0.17.0`. The `v` was a red-herring.
