### ISSUE TITLE
Bot requesting password change

### ISSUE THREAD

**Issue by andk** [andk/pause#300]
Observered in the logfiles: useragent `Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.96 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)` requests password changes.

So far I have only seen 7 comparable requests for two authors with variations in the useragent, but with the common `+http://www.google.com/bot.html` string. They are annoyances for our users. We should catch them.

**Comment by charsbar** [comment]
@andk How about this PR? Instead of blacklisting, I changed request method and added CSRF protection as well to avoid bots. https://github.com/charsbar/pause/pull/9

**Comment by andk** [comment]
Very nice, thank you! Will pull and deploy ASAP.
-- 
andreas

**Comment by andk** [comment]
Done, thanks!
