### ISSUE TITLE
Missing exception handling for sending email after password reset

### ISSUE THREAD

**Issue by andk** [andk/pause#306]
A user who had set his private email to the infamous invalid email address CENSORED tried to reset the password.  He says "it gives a server error after I go through the form". I have not reproduced, but changing his email fixed the issue for him.

**Comment by charsbar** [comment]
@andk , I could reproduce the issue locally when I intently changed my secretemail with something invalid. The actual issue was I forgot to catch a sendmail error. The PR shown above should fix this. Could you review and merge it if it looks ok?

**Comment by andk** [comment]
https://github.com/charsbar/pause/pull/11#event-2167012125
