### ISSUE TITLE
"Give up primary permissions" page is a bad idea

### ISSUE THREAD

**Issue by Grinnz** [andk/pause#307]
The "Give up primary permissions" page (https://pause.perl.org/pause/authenquery?ACTION=remove_primary) allows a user to downgrade their first-come on a module to co-maint. This should never be done, as it leaves a module in a state where there are permissions on it, but no first-come to change its permissions aside from every co-maint removing their own permissions. Instead, there should be an option to give up your first-come entirely (not assigning co-maint), and only if there are no other users with permissions. The alternative is that first-come should be transferred to someone (ADOPTME or HANDOFF if nothing else), which is already available on the "Transfer primary permissions" page.

Related: #143

**Comment by charsbar** [comment]
Related also: #229

**Comment by charsbar** [comment]
With #328, giving up primary permissions transfers their permissions to ADOPTME. If this is inconvenient, please open a new issue (and maybe refer to this). I'm closing this for now.
