### ISSUE TITLE
Don't index any packages if one package is unstable

### ISSUE THREAD

**Issue by neilb** [andk/pause#316]
Consider the following upload:

 * Distribution Foo-Bar-1.00.tar.gz
 * Contains `lib/Foo/Bar.pm` with `our $VERSION = "1.00";`
 * And `lib/Foo/Baz.pm` with `our $VERSION = "0.99_01";`

The indexer will add/update `Foo::Bar` to the index, but not `Foo::Baz`.

The danger with this is that the version number on the dist signals "this is stable" to the end-user, but they could end up writing a stable version of `Foo::Baz` with an unstable version.

So I propose that we change PAUSE so that:

> If a tarball contains one or more developer versions of packages, then nothing in the tarball will be indexed.

The uploaded would get an email telling them nothing was indexed, so even though it's a change in behaviour, I think going forward it shouldn't be much of inconvenience?

I realise that the current behaviour may have been relied on in the past, and may even be relied on by one or more tarballs currently in CPAN (adds task to todo list).

There have been Perl releases with unstable versions of modules, but PAUSE has different behaviour just for releases of Perl: unstable versions of modules in stable releases of Perl *will get indexed*.

**Comment by karenetheridge** [comment]
> There have been Perl releases with unstable versions of modules, but PAUSE has different behaviour just for releases of Perl: unstable versions of modules in stable releases of Perl will get indexed.

I'd like to see some cases where this has happened. Usually, those unstable versions are things that are dual-life, meaning that they should *already* be marked "do not index" in the metadata -- because only the cpan distribution should index them, not perl.  I would think that we should be flagging unstable versions on non-dual-life modules that appear in stable perl releases (perhaps something to add to a Porting test).

**Comment by neilb** [comment]
I'm pretty sure this came out of one of my projects to fix up weirdisms in PAUSE data. I've written various scripts over the years to look for anomalies, then I work through them and make notes as I go.

Given Karen's comment, I'd change my proposed rule to be:

> If a tarball's filename signifies a stable release, but the version number of an individual package in the tarball signifies an unstable/developer release, then if that package would otherwise be indexed (e.g. it's not already marked "do not index" in the metadata), then the whole release should be treated as a developer release, and thus not be indexed.

**Comment by rjbs** [comment]
From PTS 2023, we think we should leave the behavior as it is.  The original intent was that `_` was meant to be part of the *distribution* name, not the package version, and really people should use TRIAL.  Rather than make the behavior more complex, we would like to squeeze it out.

**Comment by neilb** [comment]
So what does it mean, and what should happen, if someone includes `_` in a package's `$VERSION`?
