### ISSUE TITLE
What to do about Unicode package names

### ISSUE THREAD

**Issue by dagolden** [andk/pause#32]
Perl 5.16 allows Unicode package names.  While we can't have Unicode package names map to .pm files, an ASCII .pm file could contain Unicode "package NAME" statements.

Should Unicode package names be detected and indexed?

**Comment by rjbs** [comment]
I think we should leave the status quo as it is.  Perl can't cope with this situation well, so I don't think PAUSE should do anything except _maybe_ ban non-ASCII packages for now.
