### ISSUE TITLE
Warn users on attempting to delete all versions of a distribution

### ISSUE THREAD

**Issue by Grinnz** [andk/pause#350]
Deleting all versions of a distribution renders it uninstallable through normal processes, only accessible from backpan. A warning should be displayed when this is requested. Related to #204

**Comment by rjbs** [comment]
From PTS 2023:  We think that warning about deleting *all* versions is complex and not all that useful.  (More below.)  On the other hand, a good warning (we think) is:  "You are deleting one or more files that appear in 02packages."

**Comment by andk** [comment]
Thanks, resolved in a different way that seems to meet the objective quite nicely (see #412). Already deployed on production pause.
