### ISSUE TITLE
Can't restore password for PAUSE account

### ISSUE THREAD

**Issue by Azq2** [andk/pause#351]
I try [restore](https://pause.perl.org/pause/query?ACTION=mailpw) password (for [ZHUMARIN](https://metacpan.org/author/ZHUMARIN)) but i dont received email. No any emails in SPAM or other folders.
I tryed wrote to andk@cpan.org and modules@perl.org, but no any reactions. 

What to do?

**Comment by Grinnz** [comment]
For posterity, this was probably a casualty of a temporary firewall issue with the email server.
