### ISSUE TITLE
Let's encrypt certs no longer working for uploads

### ISSUE THREAD

**Issue by dankogai** [andk/pause#376]
When I tried to upload Encode-3.13.tar.gz via https://www.dan.co.jp/~dankogai/cpan/Encode-3.13.tar.gz pause refused saying "certificate verify failed".  I had a same problem w/ `/usr/bin/lwp-request` of macOS Big Sur but not `/usr/bin/curl`, Chrome, Safari, or other browsers.

<img width="991" alt="pause-log0" src="https://user-images.githubusercontent.com/68812/136126087-bbba6885-bde4-497c-aa20-5743197f8507.png">

That's when I recalled Let's Encrypt's Root CA expiring the end of last month.

* https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/
* https://letsencrypt.org/docs/certificate-compatibility/
* https://scotthelme.co.uk/lets-encrypt-old-root-expiration/

This time I got thru by (turning off the http -> https redirect and) switching to http but it would be nice if we got https back to Let's Encrypt hosts.

**Comment by Grinnz** [comment]
Perhaps your openssl is the old version which doesn't like the letsencrypt workaround for the expired root cert. Tehre isn't much PAUSE can do except remove that workaround which will instead break different old clients that don't trust the new root cert.

**Comment by Grinnz** [comment]
Oh I did not understand correctly your problem description. This is regarding the "fetch a file from an URL" option for PAUSE to download a tarball from another source. So it is the certificate of the domain you enter, and the openssl version on the PAUSE server (as it is acting as the HTTP client here), which cause the issue.

**Comment by Grinnz** [comment]
To be clearer this is not related to uploading releases to PAUSE either through the web interface or cpan-upload, it is specifically the download feature of the web interface.

**Comment by rra** [comment]
This just bit me as well for the upload of App-DocKnot-6.00.tar.gz. Whatever CA database the current running PAUSE is using is out of date. Could it be using the system CA list, which perhaps has not been updated? There may be an OS update, or if you know where that certificate store is, you could import the ISRG Root X1 from https://letsencrypt.org/certificates/.

I may be able to help with more information about the OS on which PAUSE is running. Feel free to reach out to me privately (rra@cpan.org) if I can help.

**Comment by rjbs** [comment]
I thinks this is likely fixed by https://github.com/andk/pause/pull/386 or even just updating IO::Socket::SSL
