### ISSUE TITLE
02packages.details.txt does not have CLASS package anymore

### ISSUE THREAD

**Issue by skaji** [andk/pause#381]
I'm not sure I should report this to this repository, but
it seems that [CLASS](https://metacpan.org/dist/CLASS) package was removed from 02packages.details.txt recently.

```
❯ curl -s https://www.cpan.org/modules/02packages.details.txt.gz | gunzip | grep '^CLASS'

❯ echo $?
1
```

I don't think CLASS is actually removed from CPAN, or is moved to BackPAN.
Is this intentional?

**Comment by karenetheridge** [comment]
CLASS doesn't exist in the permissions database either. What user(s) and distribution was it associated with?

**Comment by skaji** [comment]
Ah, instead of CLASS package,
now 02packages.details.txt has Class package.

cc @neilb

**Comment by skaji** [comment]
According to http://neilb.org/2019/05/01/fixing-pause-permissions.html,
PAUSE indexing is case insensitive,
so I should close this issue as "this is an expected behavior".

**Comment by karenetheridge** [comment]
I think there's a problem here, because "Class" is owned by someone else, which should not have been allowed to happen:

```
Class,JDEGUEST,c
Class,MSCHWERN,f
```

```
Class                          1.001002  J/JD/JDEGUEST/Module-Generic-v0.21.3.tar.gz
```

**Comment by haarg** [comment]
This definitely looks like a bug. It seems like JDEGUEST was granted comaint when adding Class to the Module-Generic dist, but that should not have happened.

**Comment by skaji** [comment]
Oh, I thought JDEGUEST was given comaint in official channels (such as MSCHWERN gave JDEGUEST comaint).

If PAUSE accidentally gave JDEGUEST comaint,
yeah, it's definitely a bug.

**Comment by neilb** [comment]
JDEGUEST asked for co-maint on CLASS some time back. I tried various times to contact Schwern, but failed.

In the end [I gave JDEGUEST co-maint](https://www.nntp.perl.org/group/perl.modules/2022/02/msg103416.html).

I had wrongly assumed he wanted to continue on the CLASS module on CPAN. But he's used the name for something else.

I'll email him about this, and ask him to delete his release, so I can reindex Schwern's last release.

Lesson learned.

**Comment by karenetheridge** [comment]
Oh dear. I guess we should make clear that "taking over modules" doesn't mean just taking over the name, but also making an attempt to preserve the functionality and interfaces as well.

**Comment by skaji** [comment]
@neilb Thanks for the explanation.

> I had wrongly assumed he wanted to continue on the CLASS module on CPAN. But he's used the name for something else.

I think he tried keeping backward compatibility in Class package.
https://metacpan.org/release/MSCHWERN/CLASS-1.00/source/lib/CLASS.pm#L15-26
https://metacpan.org/release/JDEGUEST/Class-v1.1.4/source/lib/Class.pm#L32-45

The problem is that he renamed CLASS Class. 
Even though PAUSE indexing is case-insensitive, perl itself and CPAN clients are definitely case-SENSITIVE,
so we cannot install CLASS package or its [reverse dependencies](https://metacpan.org/module/CLASS/requires?size=500).

```
❯ cpan BackPAN::Index
...
Running install for module 'CLASS'

  The module CLASS isn't available on CPAN.

  Either the module has not yet been uploaded to CPAN, or it is
  temporary unavailable. Please contact the author to find out
  more about the status. Try 'i CLASS'.
...
```

**Comment by haarg** [comment]
There is a new release of the dist now. The dist is named CLASS, and inside lib/Class.pm it defines the CLASS package. This is not a solution to the problem. It would allow the module to "work" on Windows or MacOS where the file system is case insensitive, but not on a normal Linux system.

There isn't any reasonable way to have both CLASS and Class exist.

Additionally, Class adds a dependency on Module::Generic, which has a long list of dependencies. I don't think this is acceptable.

**Comment by haarg** [comment]
There is now [another new release](https://metacpan.org/release/JDEGUEST/CLASS-v1.1.6), changing the module name to CLASS. This would allow it to be used as CLASS again, but won't allow it to properly be used as Class. It also still requires Module::Generic, which requires perl 5.26 and a number of XS modules, and at least one module using a source filter.

I think the only reasonable option for this dist is to be reverted to what existed in the 1.00 release. If JDEGUEST is unwilling to do that, their permissions should be removed.

**Comment by karenetheridge** [comment]
I agree. There are some reverse deps of CLASS that are no doubt adversely affected by these changes.

**Comment by haarg** [comment]
I've filed https://rt.cpan.org/Ticket/Display.html?id=141675 on RT, because I'm not going to register on @jackdeguest's private gitlab instance.

**Comment by haarg** [comment]
This is mostly resolved now, with a new CLASS release that is based on the 1.00 release and doesn't include the extra modules or dependencies. The CLASS-v1.1.6 is still indexed for the other Class::* modules, so it should probably be removed, but CLASS itself is now fine.
