### ISSUE TITLE
Module not getting indexed (Paws 0.45)

### ISSUE THREAD

**Issue by pplu** [andk/pause#383]
Hi,

   Some days ago I uploaded Paws 0.45 to PAUSE (pun not intended...). After a couple of days I got advise on https://github.com/pplu/aws-sdk-perl/pull/420#issuecomment-1144038979 that the upload doesn't seem to be indexed. I have tried reindexing to no avail.

   Is this the correct channel for reporting these types of problems?

**Comment by neilb** [comment]
> Is this the correct channel for reporting these types of problems?

No – please report unexpectedly failed indexing to modules@perl.org

When you uploaded 0.45, you should have got two emails from PAUSE – one confirming the upload, and the other with the results of the indexing. What did the 2nd one say? If you no longer have that email, please request another indexing, and if it fails again, and you can't work out why from that email, please forward the email to the above email alias.

**Comment by pplu** [comment]
Thank you!
