### ISSUE TITLE
Remove workaround for mod_perl

### ISSUE THREAD

**Issue by thaljef** [andk/pause#41]
At https://github.com/andk/pause/blob/master/lib/PAUSE/pmfile.pm#L41 there is a workaround ( _cough_ hack _cough_ ) that allows mod_perl to use a magical `version.pm` file to declare all the packages in the distribution.  I'm sure it seemed reasonable at the time, but this seems way too subtle and one-off for the long term.

Could we remove that workaround and steer the mod_perl guys toward using a more normal means of package discovery (preferably, by declaring the `provides` field in the META)?

**Comment by rjbs** [comment]
I think we should probably just delete this old special case.  It's been 18 years since it was added and mod_perl 1 is super dead.

**Comment by rjbs** [comment]
From PTS 2023: We will delete this.
