### ISSUE TITLE
PAUSE key needs update (04pause.html) 

### ISSUE THREAD

**Issue by Perlbotics** [andk/pause#431]
The GPG amour text in 04pause.html is not up to date (also 04pause.gpg-export-armor).
See also [Where do I find the current PAUSE batch signing key?](https://perlmonks.org/?node_id=11153317) at Perlmonks.

**Comment by andk** [comment]
Thank you! Fixed with https://github.com/andk/pause/commit/2ec8c181d78756e1ae7588a8c8cf753df1f8687d and https://github.com/andk/pause/commit/8bb024d6b26585a0a7ef0b33ded00b8ed0735bd1
