### ISSUE TITLE
uploads hanging indefinitely in the pending state

### ISSUE THREAD

**Issue by VVelox** [andk/pause#433]
So I have several uploads that seem to have hung in the pending state.

Some are going on 5 days now where fetching them has never been attempted yet.

`https://pause.perl.org/pause/authenquery?ACTION=tail_logfile` shows `T/TO/TOKUHIROM/HTML-TreeBuilder-LibXML-0.27.tar.gz` as failing over and over. Never seems to process anything for VVELOX.

**Comment by miyagawa** [comment]
Most of the distributions displayed in gray on this page have the same issue:
https://metacpan.org/recent

**Comment by rjbs** [comment]
This was fixed quite a while ago.  Sorry for the lack of update on this ticket.
