### ISSUE TITLE
The indexer needs to spot the new class syntax and create indexing permissions based on that

### ISSUE THREAD

**Issue by neilb** [andk/pause#436]
The indexer looks for `package Foo::Bar` and then checks whether you (or anyone else) has an indexing permission on that package. And if no-one does, then you get first-come.

The new `class` feature introduces the `class Foo::Bar` syntax, and in code using this there is no `package` statement to spot.

In code which has `use feature 'class'` or `use Feature::Compat::Class`, then PAUSE should parse the class syntax. But maybe there are other modules which introduced `class` syntax but don't imply package?

This seems like a good topic for discussion at PTS 2024.

**Comment by andk** [comment]
We believe this issue has been addressed by applying #447 which has been deployed earlier today
