### ISSUE TITLE
pause.cpan.org cannot be accessed anymore (certificate problems?)

### ISSUE THREAD

**Issue by eserte** [andk/pause#437]
Since yesterday or the day before yesterday:
```
$ curl -L http://pause.cpan.org/
curl: (35) error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
```
An equivalent error happens when accessing the site in a browser.

**Comment by rspier** [comment]
Fixed.  The vast majority of traffic is via `pause.perl.org`, so this got missed when we changed how traffic is routed.

**Comment by eserte** [comment]
Confirmed. Thanks.
