### ISSUE TITLE
Errors in PAUSE version extraction

### ISSUE THREAD

**Issue by briandfoy** [andk/pause#44]
Today's package file has these errors in version numbers:

Apache::mod_pml VERSION
DBIx::Class::Fixtures::SchemaVersioned set-when-loading
Device::Gsm::Charset Revision
Mail::SpamAssassin::Conf bogus
Mail::SpamAssassin::Dns bogus
Mail::SpamAssassin::Plugin bogus
Mail::SpamAssassin::PluginHandler bogus
Mail::SpamAssassin::Reporter bogus
Net::Download::Queue::Download Net
Net::Download::Queue::DownloadStatus Net
PML::Storable VERSION
SMS::Handler::Blackhole Revision
SMS::Handler::Dispatcher Revision
SMS::Handler::Email Revision
SMS::Handler::Invoke Revision
SMS::Handler::Ping Revision
SMS::Handler::Utils Revision
SMS::Handler::Utils Revision

**Comment by rjbs** [comment]
These appear no longer to be problematic.
