### ISSUE TITLE
indexing of Package-Variant attempts to index a 'string' package

### ISSUE THREAD

**Issue by karenetheridge** [andk/pause#48]
Re http://www.nntp.perl.org/group/perl.modules/2013/05/msg85885.html --

Is there any way we can make PAUSE not think that this code means it should attempt to index a 'string' package?

https://metacpan.org/source/ETHER/Package-Variant-1.001004/lib/Package/Variant.pm#L34

Can we use something like Module::Metadata to parse the .pm to extract 'package' keywords?

**Comment by rjbs** [comment]
Nothing to do here other than pursue #28
