### ISSUE TITLE
<div> validation error in http://pause.perl.org/pause/query?ACTION=request_id

### ISSUE THREAD

**Issue by briandfoy** [andk/pause#72]
Saašha Metsärantala saasha@acc.umu.se reported a PAUSE XHTML validation error for http://pause.perl.org/pause/query?ACTION=request_id (message at http://www.nntp.perl.org/group/perl.modules/2014/01/msg88720.html)

http://validator.w3.org/check?uri=http%3a%2f%2fpause.perl.org%2fpause%2fquery%3fACTION%3drequest_id

Line 51, Column 34: document type does not allow element "div" here; missing one of "object", "applet", "map", "iframe", "button", "ins", "del" start-tag
  <div style="visibility:hidden;">If you're a bot, then type something in here:…
✉
The mentioned element is not allowed to appear in the context in which you've placed it; the other mentioned elements are the only ones that are both allowed there and can contain the element mentioned. This might mean that you need a containing element, or possibly that you've forgotten to close a previous element.

One possible cause for this message is that you have attempted to put a block-level element (such as "<p>" or "<table>") inside an inline element (such as "<a>", "<span>", or "<font>").

**Comment by charsbar** [comment]
Thanks for the report. Closing becauase PAUSE now uses HTML5 where possible.
