### ISSUE TITLE
Should not index non-lax VERSON numbers

### ISSUE THREAD

**Issue by ghost** [andk/pause#73]
Some modules in 02packages have version numbers that fail the "lax" criteria.  E.g.:

```
Mail::SpamAssassin::Dns           bogus  K/KM/KMCGRAIL/Mail-SpamAssassin-3.3.2.tar.gz
```

Anything that can't be parsed by `version->parse` should be rejected, not indexed, as otherwise various guarantees (e.g. non-decreasing version numbers) can not be guaranteed.

We should probably purge from 02packages (and the underlying table) any such examples.

**Comment by dolmen** [comment]
In the list reported by @dagolden above:
- `DBIx::Class::Fixtures::SchemaVersioned`: this package doesn't exist anymore in recent releases of `DBIx::Class::Fixtures`
- `Device::Gsm::Charset`: fixed (not anymore in the index)
- `Net::Download::Queue::*` reported as [RT#93003](https://rt.cpan.org/Ticket/Display.html?id=93003)
- `Apache::mod_pml` and `PML::Storable`: reported as [RT#106671](https://rt.cpan.org/Ticket/Display.html?id=106671)
- `SMS::Handler::*`: reported as [RT#106672](https://rt.cpan.org/Ticket/Display.html?id=106672) 

All those modules should be removed from the index.

**Comment by karenetheridge** [comment]
so, it looks like we no longer index non-lax versions, but the previous instances still exist in the index?

**Comment by dolmen** [comment]
> so, it looks like we no longer index non-lax versions, but the previous instances still exist in the index?

No, `DBIx::Class::Fixtures::SchemaVersioned` stays in the index with the bad VERSION just because newer releases of `DBIx::Class::Fixtures` don't have that module anymore, so the package stays indexed with the old release:
```
$ zgrep DBIx::Class::Fixtures 02packages.details.txt.gz 
DBIx::Class::Fixtures          1.001032  S/SK/SKAUFMAN/DBIx-Class-Fixtures-1.001032.tar.gz
DBIx::Class::Fixtures::DBI     1.001032  S/SK/SKAUFMAN/DBIx-Class-Fixtures-1.001032.tar.gz
DBIx::Class::Fixtures::DBI::mysql 1.001032  S/SK/SKAUFMAN/DBIx-Class-Fixtures-1.001032.tar.gz
DBIx::Class::Fixtures::DBI::Pg 1.001032  S/SK/SKAUFMAN/DBIx-Class-Fixtures-1.001032.tar.gz
DBIx::Class::Fixtures::External::File 1.001032  S/SK/SKAUFMAN/DBIx-Class-Fixtures-1.001032.tar.gz
DBIx::Class::Fixtures::Schema  1.001032  S/SK/SKAUFMAN/DBIx-Class-Fixtures-1.001032.tar.gz
DBIx::Class::Fixtures::SchemaVersioned set-when-loading  L/LS/LSAUNDERS/DBIx-Class-Fixtures-1.001001.tar.gz
DBIx::Class::Fixtures::Versioned 1.000002  L/LS/LSAUNDERS/DBIx-Class-Fixtures-1.000002.tar.gz
```

**Comment by andk** [comment]
Removed now.
